### ISSUE TITLE
Webhooks.senders makes python complain

### ISSUE THREAD

**Issue by Jzarecta** [pydanny/dj-webhooks#6]
I tried the usage example but couldnt get the senders submodule from webhooks:
```python
from webhooks import webhook
from webhooks.senders import targeted

@webhook(sender_callable=targeted.sender)
def basic(url, wife, husband):
    return {"husband": husband, "wife": wife}

basic(url="http://httpbin.org/post", "Danny", "Audrey")```

responde the following error:
```
>>> from webhooks import webhook
>>> from webhooks.senders import targeted
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named senders
```

**Comment by pydanny** [comment]
Use Thorn: https://medium.com/robinhood-engineering/thorn-easy-webhooks-for-python-82a78e170bdb#.u0ic1nzfg

**Comment by Jzarecta** [comment]
Actually it seems I was on the django module and not on the standalone one the pip package doesnt include the senders folder from here:
https://github.com/pydanny/webhooks/tree/master/webhooks/senders

Is probably a packaging bug:
https://pypi.python.org/pypi/webhooks/0.3.0

**Comment by pydanny** [comment]
@Jzarecta Much as I like this package, without a project I don't have the bandwidth to work on it. Hence why I recommended Thorn by @ask.
